apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runners
  namespace: gitlabrunners
  labels:
    env.skip: cloud
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      version: '0.84.1'
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 1m
  values:
    rbac:
      create: true
      rules:
        - apiGroups: [""]
          resources: ["secrets", "configmaps", "pods", "pods/attach", "pods/exec", "pods/log"]
          verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
        - apiGroups: [""]
          resources: ["services"]
          verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]

    serviceAccount:
      create: true

    gitlabUrl: https://gitlab.bnbdevelopment.hu/

    runners:
      secret: gitlab-runner-creds
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "gitlab-runners"
            image = "ubuntu:22.04"
            privileged = true
            [[runners.kubernetes.volumes.empty_dir]]
              name = "docker-certs"
              mount_path = "/certs/client"
              medium = "Memory"