apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: erettsegi-backend
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-backend
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: erettsegi-frontend
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-frontend
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: erettsegi-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: erettsegi-backend
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: erettsegi-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: erettsegi-frontend
  policy:
    semver:
      range: 1.x.x
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erettsegi-dev
  namespace: application
spec:
  chart:
    spec:
      chart: ./erettsegi-site
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m0s
  values:
    namespace: application
    development: true
    ingress:
      enabled: true
      host: dev.irodalomerettsegi.hu
    frontend:
      replicas: 3
      image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-frontend # {"$imagepolicy": "flux-system:erettsegi-frontend:name"}
      tag: 1.20.24 # {"$imagepolicy": "flux-system:erettsegi-frontend:tag"}
      hpa: false
    backend:
      replicas: 1
      image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-backend # {"$imagepolicy": "flux-system:erettsegi-backend:name"}
      tag: 1.20.25 # {"$imagepolicy": "flux-system:erettsegi-backend:tag"}
      hpa: false
    uri:
      mongo: mongodb://root:root@erettsegi-mongo-mongodb.application.svc.cluster.local:27017/material
    prometheus:
      enabled: false
      namespace: monitoring
