apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev-mongo
  namespace: application
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: '15.6.12'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    architecture: standalone
    auth:
      enabled: true
      rootUser: root
      rootPassword: root
    metrics:
      enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: dev-mongo-lb
  namespace: application
spec:
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: dev-mongo
    app.kubernetes.io/name: mongodb
  type: LoadBalancer
  loadBalancerIP: 10.10.20.219
  ports:
  - port: 27017
    targetPort: mongodb
