apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certmanager
  namespace: certmanager
spec:
  interval: 5m
  chart:
    spec:
      chart: reflector
      version: '7.1.288'
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 1m