apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-release
  namespace: service
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: "14.7.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    mode: standalone
    auth:
      existingSecret: minio-secret
      rootUserSecretKey: root-user
      rootPasswordSecretKey: root-password
    defaultBuckets: ""
    tls:
      enabled: false
    persistence:
      enabled: true
      storageClass: longhorn
    metrics:
      serviceMonitor:
        enabled: true  # for prom-operator
        namespace: monitoring # namespace of prometheus
    livenessProbe:
      enabled: false
    startupProbe:
      enabled: false
    readinessProbe:
      enabled: false
    ingress:
      enabled: true
      hostname: s3.bnbdevelopment.hu
    apiIngress:
      enabled: true
      hostname: apis3.bnbdevelopment.hu
    extraEnvVars:
    - name: MINIO_LOG_LEVEL
      value: DEBUG
    image:
      debug: true
