apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: service
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: "6.6.3"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    ingress:
      enabled: true
      className: traefik
    nextcloud:
      host: nextcloud.bnbdevelopemnt.hu
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: username
        passwordKey: password
      trustedDomains:
        - nextcloud.bnbdevelopemnt.hu
    persistence:
      nextcloudData:
        enabled: true
        storageClass: longhorn
    service:
      annotations:
        traefik.ingress.kubernetes.io/service.sticky.cookie: "true"