apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-release
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: '7.3.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: default
      interval: 1m
  values:
    replicas: 1
    # service:
    #   type: LoadBalancer
    #   port: 5000
    persistence:
      enabled: true
      storageClassName: "longhorn"
      annotations:
        helm.sh/resource-policy: "keep"