---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: arc-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller
    namespace: flux-system
  values:
    replicaCount: 1