---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Values.namespace }}
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: nestjs-app-logs
        enabled: true
        paths:
          - /var/log/app/app.log
        parsers:
          - ndjson:
              keys_under_root: true
              add_error_key: true
              overwrite_keys: true
        fields:
          log_type: application
        fields_under_root: true

      - type: filestream
        id: nestjs-error-logs
        enabled: true
        paths:
          - /var/log/app/error.log
        parsers:
          - ndjson:
              keys_under_root: true
              add_error_key: true
              overwrite_keys: true
        fields:
          log_type: error
          severity: error
        fields_under_root: true

    processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_cloud_metadata: ~

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOSTS}']
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      index: "nestjs-logs-%{+yyyy.MM.dd}"
      ssl.verification_mode: none

    setup.template.name: "nestjs-logs"
    setup.template.pattern: "nestjs-logs-*"
    setup.template.settings:
      index.number_of_shards: 1
      index.number_of_replicas: 1
    setup.template.type: index

    setup.ilm:
      enabled: false

    logging.level: info
    logging.to_files: false
    logging.to_stderr: true
