apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  config.json: |
    {
      "eventDisplayDelay" : 1800000,
      "ticketBuyDelay" : 1200000,
      "uploadPath" : "uploads"
    }