apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  config.json: |
    {
    "PY_MAIL": "agora.mail.service@gmail.com",
    "PY_DIR": "../data/email",
    "NODE_SHARE": "pdfs",
    "EMAIL_SERVER": "http://192.168.1.216:5000",
    "MONGO_URI": "mongodb://root:root@mongodb-0.mongo-release-mongodb-headless.service.svc.cluster.local:27017/?directConnection=true",
    "REDIS_URI": "redis-release-master.service.svc.cluster.local",
    "SLACK_TOKEN": "xoxp-3311554582775-3326149485602-5558132480816-b99feeab07cc6134360f9e4800c9d18b",
    "TIMES" : "./times.json",
    "PDF_FONT_FAMILY" : "media/fonts/Rubik/static/Rubik-Regular.ttf",
    "PDF_TITLE_COLOR" : "#34b019",
    "PDF_BODY_COLOR" : "#000000",
    "PDF_LEFT_MARGIN": 30,
    "PDF_RIGHT_MARGIN" : 30,
    "PDF_TOP_MARGIN" : 10,
    "PDF_BOTTOM_MARGIN" : 10,
    "PRINTABLE_PDF_WIDTH" : 500,
    "PRINTABLE_PDF_HEIGHT" : 500,
    "SEND_PDF_WIDTH" : 500,
    "SEND_PDF_HEIGHT" : 300,
    "QR_CODE_SIZE" : 80,
    "PDF_FONT_SIZE_TITLE" : 18,
    "PDF_FONT_SIZE_BODY" : 12,
    "ZIP_DIR" : "../data/zips",
    "ACCEPTED_IMAGE_EXTENSIONS" : ["PNG", "JPG", "JFIF", "JPEG", "MOV", "MP4"],
    "MAX_PAGINATOR_LIMIT" : 30,
    "TICKET_NODE_SHARE" : "/pdfs",
    "IMAGES_NODE_SHARE" : "/uploads"
    }
  times.json: |
    {
      "LOGIN_DELAY" : 0,
      "RESERVATION_TIME" : 900000,
      "TOKEN_SESSION_TIME" : 28800000,
      "MAX_LOGIN_TOKEN_DELAY" : 60000,
      "DELETABLE_EVENT" : 47336400000,
      "DELETABLE_ORDERS" : 47336400000,
      "AVAILABLE_FOR_PURCHASE_AFTER_THE_EVENT" : 1800000
    }
