{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jegyrendszer-ingressroute
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressclass }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: "Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`/`)"
    services:
    - name: web-server-svc
      port: 8080
  - kind: Rule
    match: "Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`/admin`)"
    services:
    - name: web-admin-svc
      port: 8080
  - kind: Rule
    match: "Host(`{{ .Values.ingress.hostname }}`) && (PathPrefix(`/api/v1`) || PathPrefix(`/ipn`))"
    services:
    - name: handle-server-service
      port: 3001
  - kind: Rule
    match: "Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`/socket.io`)"
    services:
    - name: handle-server-service
      port: 3001
      sticky:
        cookie:
          name: server_id
          httpOnly: true
          secure: true
{{- end -}}