---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-handler-deployment
  labels:
    app: mail-handler
    pod-security.kubernetes.io/audit: baseline
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3001"
spec:
  replicas: {{.Values.replication.mail}}
  selector:
    matchLabels:
      app: mail-handler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mail-handler
    spec:
      serviceAccountName: backend-svc-a
      imagePullSecrets:
      - name: regcred
      containers:
      - name: mail-handler
        image: "{{.Values.versions.mailer_img}}:{{.Values.versions.mailer_tag}}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        env:
        - name: CONFIGDIR
          value: "/etc/config"
        - name: NODE_ENV
          value: "production"
        - name: LOKI_URL
          value: "http://loki-release.monitoring.svc.cluster.local:3100"
        - name: TZ
          value: "Europe/Vienna"
        - name: LOKI_ENABLED
          value: "true"
        - name: REDIS_PASS
          value: "root"
        - name: PRODUCTION_CONFIGDIR
          value: "/etc/config"
        - name: MERCHANT_KEY
          value: ""
        - name: REDIS
          value: redis-release-master.service.svc.cluster.local
        envFrom:
        - secretRef:
            name: mail-secretmap
        securityContext:
          allowPrivilegeEscalation: false