apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    app: web-server
    pod-security.kubernetes.io/audit: baseline
spec:
  replicas: {{.Values.replication.web}}
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-server
    spec:
      serviceAccountName: web-svc-a
      imagePullSecrets:
      - name: regcred
      containers:
      - name: web-server
        image: "{{.Values.versions.web_img}}:{{.Values.versions.web_tag}}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Vienna"
        resources:
          limits:
            cpu: 1000m
            memory: 6Gi
          requests:
            cpu: 500m
            memory: 1Gi
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
        securityContext:
          # runAsNonRoot: true
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-svc
spec:
  selector:
    app: web-server
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-svc-a
  namespace: {{.Values.namespace}}