apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: bnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      serviceAccountName: uptime-kuma-svc-a
      volumes:
      - name: uptime-kuma-data
        persistentVolumeClaim:
          claimName: uptime-kuma-pvc
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:latest
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: uptime-kuma-data
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-svc
  namespace: bnb
spec:
  type: ClusterIP
  selector:
    app: uptime-kuma
  ports:
  - port: 80
    targetPort: 3001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: bnb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptime-kuma-svc-a
  namespace: bnb
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-ingressroute
  namespace: bnb
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: "Host(`status.bnbdevelopment.hu`) && PathPrefix(`/`)"
    kind: Rule
    services:
    - name: uptime-kuma-svc
      port: 80