---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bnbportfolio
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/bnbdevelopment/portfolio/portfolio
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bnbportfolio
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bnbportfolio
  policy:
    semver:
      range: 2.x.x
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: bnbportfolio
#   namespace: bnb
#   labels:
#     app: bnbportfolio
#     pod-security.kubernetes.io/audit: baseline
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: bnbportfolio
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
#   template:
#     metadata:
#       labels:
#         app: bnbportfolio
#     spec:
#       serviceAccountName: bnbportfolio-svc-a
#       imagePullSecrets:
#       - name: regcred-bnb
#       containers:
#       - name: bnbportfolio
#         image: europe-west3-docker.pkg.dev/bnbdevelopment/portfolio/portfolio:latest # {"$imagepolicy": "flux-system:bnbportfolio"}
#         imagePullPolicy: Always
#         resources:
#           limits:
#             cpu: 1000m
#             memory: 2Gi
#           requests:
#             cpu: 500m
#             memory: 1Gi
#         ports:
#         - containerPort: 3000
#           name: frontend-open
#         env:
#         - name: NODE_ENV
#           value: "production"
#         securityContext:
#           allowPrivilegeEscalation: false
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: bnbportfolio-svc
#   namespace: bnb
# spec:
#   selector:
#     app: bnbportfolio
#   ports:
#   - port: 3000
#     targetPort: frontend-open
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: bnbportfolio-svc-a
#   namespace: bnb