apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-release
  namespace: service
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: "14.7.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    mode: standalone # or distributed
    auth:
      rootUser: nDLGFagiosNh2g==
      rootPassword: e8bbbd769d1c5ae2cd5debbf3a504c3c77d679102c99a46cfc9c2e241ace42db62986aa8be96ef9cdeade55d2bb89522
    defaultBuckets: "" # , separated
    tls:
      enabled: false
    persistence:
      enabled: true
      storageClass: longhorn
    metrics:
      serviceMonitor:
        enabled: true  # for prom-operator
        namespace: monitoring # namespace of prometheus
    livenessProbe:
      enabled: false
    startupProbe:
      enabled: false
    readinessProbe:
      enabled: false
    ingress:
      enabled: true
      hostname: s3.bnbdevelopment.cloud
    extraEnvVars:
    - name: MINIO_API_ROOT_ACCESS
      value: off