apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-release
  namespace: service
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: "14.7.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    mode: standalone # or distributed
    auth:
      rootUser: admin
      rootPassword: admin
    defaultBuckets: "" # , separated
    tls:
      enabled: false
    persistence:
      enabled: true
      storageClass: longhorn
    metrics:
      serviceMonitor:
        enabled: true  # for prom-operator
        namespace: monitoring # namespace of prometheus
    livenessProbe:
      enabled: false
    startupProbe:
      enabled: false
    readinessProbe:
      enabled: false