apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-release
  namespace: service
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: '18.12.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    architecture: standalone
    auth:
      enabled: true
      password: "root"
    metrics:
      enabled: true
    replica:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetMemory: 70
