---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erettsegi-postgres
  namespace: service
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "16.4.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
      interval: 1m
  values:
    global:
      defaultStorageClass: longhorn
      postgresql:
        auth:
          existingSecret: postgresql-auth
    architecture: replication
    readReplicas:
      replicaCount: 2
      livenessProbe:
        enabled: false
      startupProbe:
        enabled: false
    backup:
      enabled: true
      cronjob:
        schedule: '@daily'
        storage:
          storageClass: longhorn
    auth:
      username: root
    metrics:
      enabled: true
      livenessProbe:
        enabled: false
      startupProbe:
        enabled: false
      serviceMonitor:
        enabled: true
        namespace: monitoring
      prometheusRule:
        enabled: false
        namespace: monitoring
    primary:
      livenessProbe:
        enabled: false
      startupProbe:
        enabled: false