---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erettsegi-postgres
  namespace: service
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "16.4.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    global:
      defaultStorageClass: longhorn
      postgresql:
        auth:
          existingSecret: postgresql-auth
    architecture: replication
    readReplicas:
      replicaCount: 2
    # backup:
    #   enabled: true
    auth:
      username: root
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
      prometheusRule:
        enabled: false
        namespace: monitoring