apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: erettsegi-backend
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-backend
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: erettsegi-frontend
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-frontend
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: erettsegi-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: erettsegi-backend
  policy:
    semver:
      range: 2.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: erettsegi-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: erettsegi-frontend
  policy:
    semver:
      range: 2.x.x
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erettsegi-prod
  namespace: erettsegi
spec:
  chart:
    spec:
      chart: ./erettsegi-site
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m0s
  values:
    namespace: erettsegi
    development: false
    ingress:
      enabled: true
      host: irodalomerettsegi.hu
      ingressclass: traefik-external
    frontend:
      replicas: 3
      image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-frontend # {"$imagepolicy": "flux-system:erettsegi-frontend:name"}
      tag: 2.20.114 # {"$imagepolicy": "flux-system:erettsegi-frontend:tag"}
      hpa: true
    backend:
      replicas: 2
      image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-backend # {"$imagepolicy": "flux-system:erettsegi-backend:name"}
      tag: 2.20.28 # {"$imagepolicy": "flux-system:erettsegi-backend:tag"}
      hpa: true
      livenessProbe: true
      startupProbe: true
    uri:
      mongo: mongodb://root:root@erettsegi-mongo-mongodb-0.erettsegi-mongo-mongodb-headless.service.svc.cluster.local:27017,erettsegi-mongo-mongodb-1.erettsegi-mongo-mongodb-headless.service.svc.cluster.local:27017/material
      redis: erettsegi-redis-master-0.erettsegi-redis-headless.erettsegi.svc.cluster.local
    prometheus:
      enabled: true
      namespace: monitoring
