apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bizray-frontend
  namespace: flux-system
  labels:
    env.skip: cloud
spec:
  image: europe-west3-docker.pkg.dev/bnbdevelopment/bizray/bizray-frontend
  interval: 5m
  secretRef:
    name: regcred-bnb
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bizray-frontend
  namespace: flux-system
  labels:
    env.skip: cloud
spec:
  imageRepositoryRef:
    name: bizray-frontend
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bizray-backend
  namespace: flux-system
  labels:
    env.skip: cloud
spec:
  image: europe-west3-docker.pkg.dev/bnbdevelopment/bizray/bizray-backend
  interval: 5m
  secretRef:
    name: regcred-bnb
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bizray-backend
  namespace: flux-system
  labels:
    env.skip: cloud
spec:
  imageRepositoryRef:
    name: bizray-backend
  policy:
    semver:
      range: 1.x.x
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bizray-svc-a
  namespace: bnb
  labels:
    env.skip: cloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizray-frontend
  namespace: bnb
  labels:
    app: bizray-frontend
    pod-security.kubernetes.io/audit: baseline
    env.skip: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizray-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bizray-frontend
    spec:
      serviceAccountName: bizray-svc-a
      imagePullSecrets:
      - name: regcred-bnb
      containers:
      - name: bizray-frontend
        image: europe-west3-docker.pkg.dev/bnbdevelopment/bizray/bizray-frontend:1.0.34 # {"$imagepolicy": "flux-system:bizray-frontend"}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 80
          name: frontend-open
        env:
        - name: NODE_ENV
          value: "production"
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: bizray-frontend-svc
  namespace: bnb
  labels:
    env.skip: cloud
spec:
  selector:
    app: bizray-frontend
  ports:
  - port: 80
    targetPort: frontend-open
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizray-backend
  namespace: bnb
  labels:
    app: bizray-backend
    pod-security.kubernetes.io/audit: baseline
    env.skip: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizray-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bizray-backend
    spec:
      serviceAccountName: bizray-svc-a
      imagePullSecrets:
      - name: regcred-bnb
      containers:
      - name: bizray-backend
        image: europe-west3-docker.pkg.dev/bnbdevelopment/bizray/bizray-backend:1.0.37 # {"$imagepolicy": "flux-system:bizray-backend"}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 3000
          name: backend-open
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgresql+psycopg://admin:admin@192.168.88.46:5432/bizray"
        - name: REDIS_HOST
          value: "192.168.88.46"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bizray-creds
              key: JWT_SECRET
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: bizray-creds
              key: API_KEY
        - name: WSDL_URL
          valueFrom:
            secretKeyRef:
              name: bizray-creds
              key: WSDL_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bizray-creds
              key: REDIS_PASSWORD
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: bizray-backend-svc
  namespace: bnb
  labels:
    env.skip: cloud
spec:
  selector:
    app: bizray-backend
  ports:
  - port: 3000
    targetPort: backend-open
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bizray-ingressroute
  namespace: bnb
  annotations:
    kubernetes.io/ingress.class: traefik-external
  labels:
    env.skip: cloud
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: "Host(`bizray.bnbdevelopment.hu`) && PathPrefix(`/`)"
      kind: Rule
      priority: 10
      services:
        - name: bizray-frontend-svc
          port: 80
          # middlewares:
          #   - name: ak-outpost-onprem-cluster
          #     namespace: authentik
    # - kind: Rule
    #   match: "Host(`bizray.bnbdevelopment.hu`) && PathPrefix(`/outpost.goauthentik.io/`)"
    #   priority: 15
    #   services:
    #     - kind: Service
    #       name: ak-outpost-onprem-cluster
    #       namespace: authentik
    #       port: 9000
    #       passHostHeader: true
    - match: "Host(`apibizray.bnbdevelopment.hu`) && PathPrefix(`/`)"
      kind: Rule
      services:
        - name: bizray-backend-svc
          port: 3000
