apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: matekerettsegi-backend
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/bnbdevelopment/matekerettsegi/backend
  interval: 5m
  secretRef:
    name: regcred-bnb
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: matekerettsegi-generator
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/bnbdevelopment/matekerettsegi/generator
  interval: 5m
  secretRef:
    name: regcred-bnb
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: matekerettsegi-frontend
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/bnbdevelopment/matekerettsegi/frontend
  interval: 5m
  secretRef:
    name: regcred-bnb
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: matekerettsegi-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: matekerettsegi-backend
  policy:
    semver:
      range: 0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: matekerettsegi-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: matekerettsegi-frontend
  policy:
    semver:
      range: 0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: matekerettsegi-generator
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: matekerettsegi-generator
  policy:
    semver:
      range: 0.x.x
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: matekerettsegi
  namespace: flux-system
spec:
  interval: 5m
  url: oci://europe-west3-docker.pkg.dev/bnbdevelopment/charts/matekerettsegi
  provider: generic
  secretRef:
    name: regcred-bnb
  ref:
    semver: ">=0.2.0 <1.0.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matekerettsegi
  namespace: bnb
  labels:
    env.skip: cloud
spec:
  chartRef:
    kind: OCIRepository
    name: matekerettsegi
    namespace: flux-system
  interval: 5m
  timeout: 15m
  values:
    imagePullSecrets:
      - name: regcred-bnb
    # hostname, routing
    routing:
      host: matekx.hu
    traefik:
      annotations:
        kubernetes.io/ingress.class: traefik-external
      tls:
        enabled: false
    # images
    web:
      image:
        repository: europe-west3-docker.pkg.dev/bnbdevelopment/matekerettsegi/frontend # {"$imagepolicy": "flux-system:matekerettsegi-frontend:name"}
        tag: "v0.39.0" # {"$imagepolicy": "flux-system:matekerettsegi-frontend:tag"}
    api:
      image:
        repository: europe-west3-docker.pkg.dev/bnbdevelopment/matekerettsegi/backend # {"$imagepolicy": "flux-system:matekerettsegi-backend:name"}
        tag: "v0.35.0" # {"$imagepolicy": "flux-system:matekerettsegi-backend:tag"}
      env:
        WEB_ORIGIN: https://matekx.hu
        BETTER_AUTH_URL: https://matekx.hu
      extraEnv:
        - name: AUTHENTIK_DISCOVERY_URL
          value: https://auth.bnbdevelopment.hu/application/o/matekerettsegi-bnb/.well-known/openid-configuration
        - name: AUTHENTIK_CLIENT_ID
          value: vwMCrswVNEhYEiGfFbcCpKlMaP6vLU4wrqtRgLGL
        - name: AUTHENTIK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: matekerettsegi-runtime
              key: AUTHENTIK_CLIENT_SECRET
    generator:
      image:
        repository: europe-west3-docker.pkg.dev/bnbdevelopment/matekerettsegi/generator # {"$imagepolicy": "flux-system:matekerettsegi-generator:name"}
        tag: "v0.21.0" # {"$imagepolicy": "flux-system:matekerettsegi-generator:tag"}

# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: bnbbilling-ingressroute
#   namespace: bnb
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#   - websecure
#   routes:
#   - kind: Rule
#     match: Host(`billing.bnbdevelopment.hu`) && PathPrefix(`/api/`)
#     services:
#     - name: bnbbilling-backend
#       port: 80
#   - kind: Rule
#     match: Host(`billing.bnbdevelopment.hu`) && PathPrefix(`/`)
#     services:
#     - name: bnbbilling-frontend
#       port: 80
