apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demosite
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: '20.1.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    global:
      storageClass: longhorn
    wordpressUsername: admin
    wordpressPassword: admin
    wordpressConfigureCache: true
    replicaCount: 2
    updateStrategy:
      type: RollingUpdate
    service:
      type: CluserIP
    persistence:
      enabled: true
    metrics:
      enabled: true
    mariadb:
      architecture: standalone
