apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web-admin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: web-admin
  policy:
    semver:
      range: '>=1.0.0'