apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jegyrendszer-release
  namespace: default
spec:
  chart:
    spec:
      chart: ./jegyrendszer
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m0s
  values:
    handle:
      storageClass: longhorn
    replication:
      web: 5
      admin: 2
      handle: 3
    versions:
      handle_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/handle-server # {"$imagepolicy": "flux-system:handle:name"}
      handle_tag: 1.20.46 # {"$imagepolicy": "flux-system:handle:tag"}
      web_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-public # {"$imagepolicy": "flux-system:web-public:name"}
      web_tag: 1.20.6 # {"$imagepolicy": "flux-system:web-public:tag"}
      web_admin: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-admin # {"$imagepolicy": "flux-system:web-admin:name"}
      web_admin_tag: 1.20.12 # {"$imagepolicy": "flux-system:web-admin:tag"}
