apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jegyrendszer-release
  namespace: default
spec:
  chart:
    spec:
      chart: ./jegyrendszer
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m0s
  values:
    handle:
      storageClass: longhorn
    replication:
      web: 5
      handle: 3
    versions:
      handle_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/handle-server # {"$imagepolicy": "flux-system:handle:name"}
      handle_tag: 1.20.19 # {"$imagepolicy": "flux-system:handle:tag"}
      web_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-server # {"$imagepolicy": "flux-system:web:name"}
      web_tag: 1.11.0 # {"$imagepolicy": "flux-system:web:tag"}
