apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-sync
  namespace: jegyrendszer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: election-sync
  template:
    metadata:
      labels:
        app: election-sync
    spec:
      serviceAccountName: election-svca
      imagePullSecrets:
      - name: regcred
      containers:
      - name: election-sync
        image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/election-sync:1.0 # {"$imagepolicy": "flux-system:election-flux"}
        resources:
          limits:
            memory: "2Gi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: election-svca
  namespace: jegyrendszer
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: election-flux
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/election-sync
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: election-flux
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: election-flux
  policy:
    semver:
      range: '>=1.0.0'