apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jegyrendszer-release
  namespace: jegyrendszer
spec:
  chart:
    spec:
      chart: ./jegyrendszer
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m0s
  values:
    namespace: jegyrendszer
    pvcsize: 10Gi
    handle:
      storageClass: longhorn
    replication:
      web: 5
      admin: 2
      handle: 3
      mail: 2
    versions:
      handle_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/handle-server # {"$imagepolicy": "flux-system:handle:name"}
      handle_tag: 1.20.85 # {"$imagepolicy": "flux-system:handle:tag"}
      mail_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/mail-handler # {"$imagepolicy": "flux-system:mail:name"}
      mail_tag: 1.20.10 # {"$imagepolicy": "flux-system:mail:tag"}
      web_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-public # {"$imagepolicy": "flux-system:web-public:name"}
      web_tag: 1.20.19 # {"$imagepolicy": "flux-system:web-public:tag"}
      web_admin: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-admin # {"$imagepolicy": "flux-system:web-admin:name"}
      web_admin_tag: 1.20.27 # {"$imagepolicy": "flux-system:web-admin:tag"}
    ingress:
      enabled: true
      hostname: jegy-agorasavaria.hu
