apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sztv-mongo
  namespace: sztv
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: '14.8.3'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    architecture: standalone
    image:
      tag: 4.2.21-debian-10-r8
    auth:
      enabled: true
      rootUser: root
      rootPassword: ""
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false