apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web-public
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: web-public
  policy:
    semver:
      range: '>=1.0.0'