namespace: erettsegi
development: true
ingress:
  enabled: true
  host: irodalomerettsegi.hu
  ingressclass: traefik-external
frontend:
  replicas: 1
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-frontend
  tag: 1.20.24
  hpa: true
backend:
  replicas: 1
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-backend
  tag: 1.20.21
  hpa: true
  livenessProbe: true
  startupProbe: true
statistics:
  enabled: true
  replicas: 1
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-statistics
  tag: 1.20.1
  mongo: mongodb://root:root@erettsegi-mongo-mongodb.application.svc.cluster.local:27017/erettsegi
uri:
  mongo: mongodb://root:root@erettsegi-mongo-mongodb.application.svc.cluster.local:27017/material
  redis: ''
prometheus:
  enabled: true
  namespace: monitoring