namespace: erettsegi
ingress:
  enabled: true
  host: irodalomerettsegi.hu
frontend:
  replicas: 1
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-frontend
  tag: 1.20.24
backend:
  replicas: 1
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-backend
  tag: 1.20.21
uri:
  mongo: mongodb://root:root@erettsegi-mongo-mongodb.application.svc.cluster.local:27017/
prometheus:
  enabled: true
  namespace: monitoring