apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: '2024.4.2'
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
      interval: 1m
  values:
    authentik:
        secret_key: juAg+C7lZV0Bz7y9GofBPt4pz4lZG7yRFJOxA/lEljxCSEMpva5YEP7gDYXNMoJJ7VXTTSn1SY6ZT/dk
        error_reporting:
            enabled: true
        postgresql:
            password: 90b3b547560b3fd1cf98bb8a7aa2a064f45fa721
    server:
        ingress:
            ingressClassName: traefik
            enabled: true
            hosts:
                - authentik.paks.local
    postgresql:
        enabled: true
        auth:
            password: 90b3b547560b3fd1cf98bb8a7aa2a064f45fa721
    redis:
        enabled: true