{
 "title": "Prem-Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Load & Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Load - PVE1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"192.168.88.253:9100\",job=\"proxmox_nodeexporter\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"192.168.88.253:9100\",job=\"proxmox_nodeexporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load - PVE2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"192.168.88.250:9100\",job=\"proxmox_nodeexporter\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"192.168.88.250:9100\",job=\"proxmox_nodeexporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load - PVE3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"192.168.88.252:9100\",job=\"proxmox_nodeexporter\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"192.168.88.252:9100\",job=\"proxmox_nodeexporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  node_hwmon_temp_celsius{job=\"proxmox_nodeexporter\"}\n  * on(instance, chip) group_left(chip_name)\n  node_hwmon_chip_names{job=\"proxmox_nodeexporter\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure - PVE1",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"192.168.88.253:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"192.168.88.253:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"192.168.88.253:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=\"192.168.88.253:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "Pressure - PVE2",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"192.168.88.250:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"192.168.88.250:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"192.168.88.250:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=\"192.168.88.250:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  node_hwmon_temp_celsius{job=\"proxmox_nodeexporter\"}\n  * on(instance, chip) group_left(chip_name)\n  node_hwmon_chip_names{job=\"proxmox_nodeexporter\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UPS Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_load", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"proxmox_nodeexporter\"} - node_boot_time_seconds{job=\"proxmox_nodeexporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pressure - PVE3",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"192.168.88.252:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"192.168.88.252:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"192.168.88.252:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=\"192.168.88.252:9100\", job=\"proxmox_nodeexporter\"}[$__rate_interval])",
     "legendFormat": "Irq"
    }
   ]
  },
  { "title": "Power Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.sonoff_100255fc7c_power\"}",
     "legendFormat": "Plug"
    },
    {
     "expr": "nut_real_power_watts{instance=\"192.168.88.253:3493\"}",
     "legendFormat": "UPS"
    },
    {
     "expr": "scalar(homeassistant_sensor_power_w{entity=\"sensor.sonoff_100255fc7c_power\"}) \n+ scalar(nut_real_power_watts{instance=\"192.168.88.253:3493\"})\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_status", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Power status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "homeassistant_switch_state{entity=\"switch.sonoff_100255fc7c\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Today (kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{entity=\"sensor.sonoff_100255fc7c_energy_day\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current (A)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_current_a{entity=\"sensor.sonoff_100255fc7c_current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power (W)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.sonoff_100255fc7c_power\"}",
     "legendFormat": "Plug"
    },
    {
     "expr": "nut_real_power_watts{instance=\"192.168.88.253:3493\"}",
     "legendFormat": "UPS"
    }
   ]
  },
  {
   "title": "Total (W)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(homeassistant_sensor_power_w{entity=\"sensor.sonoff_100255fc7c_power\"}) \n+ scalar(nut_real_power_watts{instance=\"192.168.88.253:3493\"})\n",
     "legendFormat": "Plug"
    }
   ]
  }
 ]
}