---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erettsegi-mongo
  namespace: erettsegisite
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: "14.8.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    architecture: standalone
    auth:
      enabled: true
      rootUser: root
      rootPassword: "root"
    image:
      tag: 4.2.21-debian-10-r8
    metrics:
      enabled: true
    readinessProbe:
      timeoutSeconds: 5
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: erettsegi-mongo
#   namespace: erettsegisite
# spec:
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/component: mongodb
#     app.kubernetes.io/instance: mongo-release
#     app.kubernetes.io/name: mongodb
#   ports:
#     - port: 27017
#       targetPort: 27017
