apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certmanager
  namespace: certmanager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.16.2'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: true
    replicaCount: 3
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 9.9.9.9