---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bnbdevelopment-cloud
  namespace: certmanager
spec:
  secretName: local-bnbdevelopment-cloud-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.bnbdevelopment.cloud"
  dnsNames:
  - "local.bnbdevelopment.cloud"
  - "*.local.bnbdevelopment.cloud"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bnbdevelopment-cloud-prod
  namespace: certmanager
spec:
  secretName: local-bnbdevelopment-cloud-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.bnbdevelopment.cloud"
  dnsNames:
  - "local.bnbdevelopment.cloud"
  - "*.local.bnbdevelopment.cloud"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bnbdevelopment-hu
  namespace: certmanager
spec:
  secretName: local-bnbdevelopment-hu-staging-tls
  issuerRef:
    name: letsencrypt-staging-hu
    kind: ClusterIssuer
  commonName: "*.local.bnbdevelopment.hu"
  dnsNames:
  - "local.bnbdevelopment.hu"
  - "*.local.bnbdevelopment.hu"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: local-bnbdevelopment-hu-prod
#   namespace: certmanager
# spec:
#   secretName: local-bnbdevelopment-hu-tls
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "*.local.bnbdevelopment.hu"
#   dnsNames:
#   - "local.bnbdevelopment.hu"
#   - "*.local.bnbdevelopment.hu"
#   secretTemplate:
#     annotations:
#       reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
#       reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"
#       reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
#       reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "certmanager,monitoring,longhorn-system,traefik-system"