---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: certmanager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: benceanya05@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: benceanya05@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "bnbdevelopment.cloud"
            - "bnbdevelopment.hu"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: certmanager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benceanya05@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: benceanya05@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "bnbdevelopment.cloud"
            - "bnbdevelopment.hu"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-hu
  namespace: certmanager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: benceanya05@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-hu
    solvers:
      - dns01:
          cloudflare:
            email: benceanya05@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "bnbdevelopment.hu"
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production-hu
#   namespace: certmanager
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: benceanya05@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-production-hu
#     solvers:
#       - dns01:
#           cloudflare:
#             email: benceanya05@gmail.com
#             apiTokenSecretRef:
#               name: cloudflare-token-secret
#               key: cloudflare-token
#         selector:
#           dnsZones:
#             - "bnbdevelopment.hu"