---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erettsegi-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: erettsegi-frontend
    pod-security.kubernetes.io/audit: baseline
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: erettsegi-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: erettsegi-frontend
    spec:
      serviceAccountName: erettsegi-frontend-svc-a
      imagePullSecrets:
      - name: regcred-bnb
      containers:
      - name: erettsegi-frontend
        image: "europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-frontend:{{.Values.frontend.tag}}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 3000
          name: frontend-open
        env:
        - name: NODE_ENV
          value: "production"
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: erettsegi-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: erettsegi-frontend
  ports:
  - port: 3000
    targetPort: frontend-open
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: erettsegi-frontend-svc-a
  namespace: {{ .Values.namespace }}