# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: erettsegi-ingressroute
#   namespace: {{ .Values.namespace }}
# spec:
#   entryPoints:
#     - web
#     - websecure
#   routes:
#   - kind: Rule
#     match: "Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/`)"
#     services:
#     - kind: Service
#       name: erettsegi-frontend-service
#       namespace: {{ .Values.namespace }}
#       port: 3000
#   - kind: Rule
#     match: "Host(`api.{{ .Values.ingress.host }}`) && PathPrefix(`/`) "
#     services:
#     - kind: Service
#       name: erettsegi-backend
#       namespace: {{ .Values.namespace }}
#       port: 3000