---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erettsegi-site-ingress
  namespace: {{.Values.namespace}}
  labels:
    name: erettsegi-site-ingress
spec:
  rules:
  # - host: {{.Values.ingress.host}}
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/"
  #       backend:
  #         service:
  #           name: erettsegi-frontend-service
  #           port:
  #             number: 3000
  - host: "api.{{.Values.ingress.host}}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: erettsegi-backend
            port:
              number: 3000