---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: erettsegi-ingressroute
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressclass }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: "Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/`)"
    kind: Rule
    services:
    - name: erettsegi-frontend-service
      port: 3000
  - kind: Rule
    match: "Host(`api.{{ .Values.ingress.host }}`) && PathPrefix(`/`) "
    services:
    - name: erettsegi-backend
      port: 3000
{{ if .Values.statistics.enabled }}
  - kind: Rule
    match: "Host(`api.{{ .Values.ingress.host }}`) && PathPrefix(`/stats`) "
    services:
    - name: erettsegi-statistics
      port: 3000
{{ end }}