{{- if .Values.prometheus.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: erettsegi-backend-servicemon
  namespace: {{.Values.prometheus.namespace}}
  labels:
    release: prom
    app.kubernetes.io/name: erettsegi
    prometheus: system-monitoring-prometheus
spec:
  selector:
    matchLabels:
      app: erettsegi-backend
  namespaceSelector:                                                                                                                                    │
    matchNames:                                                                                                                                         │
    - {{ .Values.namespace }}
  endpoints:
    - port: backend-open
      path: /api/v1/metrics
      scheme: http
      interval: 30s
{{- end -}}