{{- if .Values.prometheus.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: erettsegi-backend
  namespace: {{.Values.prometheus.namespace}}
  labels:
    release: prom
    app.kubernetes.io/name: erettsegi
    app.kubernetes.io/instance: erettsegib-release
    prometheus: system-monitoring-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: erettsegib-release
      app.kubernetes.io/name: erettsegib
  namespaceSelector:
    matchNames:                                                                                                                                         
    - {{ .Values.namespace }}
  endpoints:
    - port: backend-open
      path: /api/v1/metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: erettsegi-statistics
  namespace: {{.Values.prometheus.namespace}}
  labels:
    release: prom
    app.kubernetes.io/name: erettsegis
    app.kubernetes.io/instance: erettsegis-release
    prometheus: system-monitoring-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: erettsegis-release
      app.kubernetes.io/name: erettsegis
  namespaceSelector:
    matchNames:                                                                                                                                         
    - {{ .Values.namespace }}
  endpoints:
    - port: api
      path: /metrics
      interval: 30s
{{- end -}}