{{ if .Values.statistics.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erettsegi-statistics
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/instance: erettsegis-release
    app.kubernetes.io/name: erettsegis
    pod-security.kubernetes.io/audit: baseline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: erettsegis-release
      app.kubernetes.io/name: erettsegis
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: erettsegis-release
        app.kubernetes.io/name: erettsegis
    spec:
      serviceAccountName: erettsegi-statistics-svc-a
      imagePullSecrets:
      - name: regcred
      containers:
      - name: erettsegi-backend
        image: "europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/erettsegi-statistics:{{.Values.statistics.tag}}" 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 3000
          name: api
        envFrom:
        - secretRef:
            name: erettsegi-statistics-secret
        env:
        - name: MONGODB_URI
          value: {{ .Values.statistics.mongo }}
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: erettsegi-statistics
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: erettsegis-release
    app.kubernetes.io/name: erettsegis
spec:
  selector:
    app.kubernetes.io/instance: erettsegis-release
    app.kubernetes.io/name: erettsegis
  ports:
  - name: api
    port: 3000
    protocol: TCP
    targetPort: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: erettsegi-statistics-svc-a
  namespace: {{ .Values.namespace }}
{{ end }}