---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-repo
        namespace: flux-system
      interval: 1m
  values:
    replicas: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kibana
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-repo
        namespace: flux-system
      interval: 1m
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.88.110
      port: 5601
    ingress:
      enabled: true
      hosts:
      - host: kibana.paks.local
        paths:
        - /