apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-release
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '6.18.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
      interval: 1m
  values:
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      auth_enabled: false
    singleBinary:
      replicas: 1