apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-release
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '6.18.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
      interval: 1m
  values:
    deploymentMode: SingleBinary
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem
          schema: v13
      auth_enabled: false
    singleBinary:
      replicas: 1
    read:
      replicas: 0
    backend:
      replicas: 0
    write:
      replicas: 0