---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio-scrape
  namespace: monitoring
  labels:
    release: prometheus
spec:
  staticConfigs:
    - targets: 
        - "192.168.88.65:9000"
  metricsPath: /minio/v2/metrics/cluster
  scheme: HTTP
  authorization:
    credentials:
      name: minio-bearer-token
      key: token-node1
# ---
# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: minio-scrape
#   namespace: monitoring
#   labels:
#     release: prometheus
# spec:
#   staticConfigs:
#     - targets: 
#         - "192.168.88.66:9000"
#   metricsPath: /minio/v2/metrics/cluster
#   scheme: HTTP
#   authorization:
#     credentials:
#       name: minio-bearer-token
#       key: token-node2
# ---
# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: minio-scrape
#   namespace: monitoring
#   labels:
#     release: prometheus
# spec:
#   staticConfigs:
#     - targets: 
#         - "192.168.88.67:9000"
#   metricsPath: /minio/v2/metrics/cluster
#   scheme: HTTP
#   authorization:
#     credentials:
#       name: minio-bearer-token
#       key: token-node3