---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: static-config
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    release: prom
spec:
  staticConfigs:
    - labels:
        job: cloudflare_tunnel
      targets:
        - 192.168.88.41:60123
        - 192.168.88.42:60123
        - 192.168.88.43:60123
        - 192.168.88.44:60123
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: patroni
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    release: prom
spec:
  staticConfigs:
    - labels:
        job: patroni
      targets:
        - 192.168.88.56:8008
        - 192.168.88.57:8008
        - 192.168.88.58:8008
  scheme: HTTPS
  tlsConfig:
    insecureSkipVerify: true
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: postgres-ha
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    release: prom
spec:
  staticConfigs:
    - labels:
        job: postgres-ha
      targets:
        - 192.168.88.56:9187
        - 192.168.88.57:9187
        - 192.168.88.58:9187
# ---
# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: mc-scrapeconfig
#   namespace: monitoring
#   labels:
#     prometheus: system-monitoring-prometheus
#     release: prom
# spec:
#   staticConfigs:
#     - labels:
#         job: papermc
#       targets:
#         - 10.10.20.106:9940
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    release: prom
spec:
  staticConfigs:
    - labels:
        job: nut
      targets:
        - 192.168.88.253:3493
  metricsPath: /metrics
  honorTimestamps: true
  scrapeTimeout: 10s
  scrapeInterval: 30s
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: 192.168.88.253:9995