---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: charts-oci-tcp
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`charts.bnbdevelopment.hu`)
      services:
        - name: oci-forward
          port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: oci-forward
  namespace: traefik-system
spec:
  type: ExternalName
  externalName: europe-west3-docker.pkg.dev
  ports:
    - port: 443
      protocol: TCP
