# Networking
[haproxy]
lb1 ansible_host=192.168.88.6 ansible_user=root # pve1
lb2 ansible_host=192.168.88.7 ansible_user=root # pve1
lb3 ansible_host=192.168.88.8 ansible_user=root # pve2
lb4 ansible_host=192.168.88.9 ansible_user=root # pve3

[cloudflared]
tunnel1 ansible_host=192.168.88.41 ansible_user=root
tunnel2 ansible_host=192.168.88.42 ansible_user=root
tunnel3 ansible_host=192.168.88.43 ansible_user=root
tunnel4 ansible_host=192.168.88.44 ansible_user=root

# Talos Cluster
[servers]
server1 ansible_host=192.168.88.11
server2 ansible_host=192.168.88.12
server3 ansible_host=192.168.88.13

[agents]
agent1 ansible_host=192.168.88.14
agent2 ansible_host=192.168.88.15
agent3 ansible_host=192.168.88.16

# Docker
[docker]
docker1 ansible_host=192.168.88.45
docker3 ansible_host=192.168.88.47

# Databases
[postgres]
postgres1 ansible_host=192.168.88.56
postgres2 ansible_host=192.168.88.57 # on pve3
postgres3 ansible_host=192.168.88.58 # on pve2

[other]
mail ansible_host=192.168.88.71