apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik/ns.yaml
- authentik/authentik.yaml
- bnbdevelopment/bnb.yaml
- bnbdevelopment/bnb-portfolio.yaml
- bnbdevelopment/bnb-docs.yaml
- bnbdevelopment/bnbbilling.yaml
- bnbdevelopment/capslop.yaml
- certmanager/certns.yaml
- certmanager/certificate.yaml
- certmanager/certmanager.yaml
- certmanager/ingress.yaml
- certmanager/issuer.yaml
- default/repositories.yaml
- erettsegisite/erettsegi.yaml
- erettsegisite/erettsegisite.yaml
- flux-system/flux-system-automation.yaml
- git/git.yaml
- git/forgejo.yaml
# - git/forgejo-runner.yaml
- gitlab/ns.yaml
- gitlab/gitlab.yaml
- gitlabrunners/ns.yaml
- gitlabrunners/gitlab-runners.yaml
- invoicing/ns.yaml
- invoicing/invoiceninja.yaml
# - keycloak/ns.yaml
# - keycloak/keycloak.yaml
- logging/logging.yaml
# - logging/elk.yaml
- monitoring/clickhouse.yaml
- monitoring/glitchtip.yaml
- monitoring/signoz.yaml
- monitoring/monitoring.yaml
# - monitoring/loki-release.yaml
- monitoring/prom-stack.yaml
# - monitoring/dependencytrack.yaml
# - traefik-system/ir-portainer.yaml
- traefik-system/ir-proxmox.yaml
- utility/reflector.yaml
- webstats/webstats-ns.yaml
- webstats/webstats-oci.yaml
- webstats/webstats-images.yaml
- webstats/webstats.yaml
