apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik/ns.yaml
- authentik/authentik.yaml
- bnbdevelopment/bnb.yaml
- bnbdevelopment/bnb-portfolio.yaml
- bnbdevelopment/bnb-docs.yaml
- certmanager/certns.yaml
- certmanager/certificate.yaml
- certmanager/certmanager.yaml
- certmanager/ingress.yaml
- certmanager/issuer.yaml
- default/repositories.yaml
- erettsegisite/erettsegi.yaml
- erettsegisite/erettsegisite.yaml
- flux-system/flux-system-automation.yaml
- keycloak/ns.yaml
# - keycloak/keycloak.yaml
- monitoring/monitoring.yaml
# - monitoring/loki-release.yaml
- monitoring/prom-stack.yaml
# - traefik-system/ir-portainer.yaml
- traefik-system/ir-proxmox.yaml
- utility/reflector.yaml
- webstats/webstats-ns.yaml
- webstats/webstats-images.yaml
# - webstats/webstats.yaml