---
# Used by: bitnami images
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-repo
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
# Used by: loki
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-repo
  namespace: flux-system
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
# Used by: prometheus & grafana
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-repo
  namespace: flux-system
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
# Used by: certmanager
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.jetstack.io
---
# Used by: reflector
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack
  namespace: flux-system
spec:
  interval: 5m
  url: https://emberstack.github.io/helm-charts
---
# Used by: authentik
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik-repo
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.goauthentik.io/
---
# Used by: ELK stack
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic-repo
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.elastic.co