---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: backend
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/backend
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mailer
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/mailer
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web-admin
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-admin
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web-public
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-frontend
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: web-public
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web-admin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: web-admin
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: backend
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mailer
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mailer
  policy:
    semver:
      range: '>=1.0.0'