apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jegyrendszer-release
  namespace: jegyrendszer
spec:
  chart:
    spec:
      chart: ./jegyrendszer
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m0s
  values:
    namespace: jegyrendszer
    pvcsize: 10Gi
    handle:
      storageClass: longhorn
    autoscaler:
      enabled: false
    replication:
      web: 1
      admin: 1
      handle: 1
      mail: 1
    versions:
      handle_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/backend # {"$imagepolicy": "flux-system:backend:name"}
      handle_tag: 2.20.111 # {"$imagepolicy": "flux-system:backend:tag"}
      web_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-frontend # {"$imagepolicy": "flux-system:web-public:name"}
      web_tag: 2.20.13 # {"$imagepolicy": "flux-system:web-public:tag"}
      web_admin: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/web-admin # {"$imagepolicy": "flux-system:web-admin:name"}
      web_admin_tag: 2.20.14 # {"$imagepolicy": "flux-system:web-admin:tag"}
      mailer_img: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/mailer # {"$imagepolicy": "flux-system:mailer:name"}
      mailer_tag: 2.20.11 # {"$imagepolicy": "flux-system:mailer:tag"}
    ingress:
      enabled: true
      hostname: jegy-agorasavaria.hu
      ingressclass: traefik-external
