apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongo-jegyrendszer
  namespace: jegyrendszer
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: "16.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    architecture: replicaset
    replicaCount: 2
    auth:
      enabled: true
      rootUser: root
      rootPassword: "root"
    image:
      tag: 4.2.21-debian-10-r8
    metrics:
      enabled: true
      collector:
        all: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
      prometheusRule:
        enabled: false
        namespace: monitoring
    readinessProbe:
      timeoutSeconds: 5
    arbiter:
      enabled: false