name: "Test push to MinIO"

on: workflow_dispatch
jobs:
  build-push-gcr:
    name: Push something to minio
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./app
    env:
      IMAGE_NAME: IMAGE
      PROJECT_ID: GCP_PROJECT_ID
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Write something funny
      run: |-
        echo 'asdasdasdasdasdasdasd' > myfile
        pwd
    - name: Install AWS CLI
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install awscli
    - name: Upload APK to Minio via AWS CLI
      env:
        AWS_ACCESS_KEY_ID: "2kAU2JKGITdFaJDsm2xy"
        AWS_SECRET_ACCESS_KEY: "cDxnEueNBve5HdawDYgsj7QHu6G2EvVRi9ILEPkf"
        MINIO_BUCKET: jegyrendszer-app
        MINIO_ENDPOINT: https://api.s3.bnbdevelopment.cloud
      run: |
        aws --endpoint-url $MINIO_ENDPOINT s3 cp myfile s3://$MINIO_BUCKET/myfile
