name: "Test push to MinIO"

on: workflow_dispatch
jobs:
  build-push-gcr:
    name: Push something to minio
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./app
    env:
      IMAGE_NAME: IMAGE
      PROJECT_ID: GCP_PROJECT_ID
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Write something funny
      run: |-
        echo 'asdasdasdasdasdasdasd' > myfile
        pwd
    # - name: Upload APK to Minio via AWS CLI
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
    #     MINIO_BUCKET: BUCKET_NAME
    #     MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
    #   run: |
    #       aws --endpoint-url $MINIO_ENDPOINT s3 cp myfile s3://$MINIO_BUCKET/app-release.apk
