name: "Test push to MinIO"

on: workflow_dispatch
jobs:
  build-push-gcr:
    name: Push something to minio
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./app
    env:
      IMAGE_NAME: IMAGE
      PROJECT_ID: GCP_PROJECT_ID
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Write something funny
      run: |-
        echo 'asdasdasdasdasdasdasd' > myfile
        pwd
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade
    - name: Test MinIO endpoint connection
      run: |
        curl -I https://apis3.bnbdevelopment.cloud
    - name: Upload APK to Minio via AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ""
        AWS_SECRET_ACCESS_KEY: ""
        MINIO_BUCKET: bucket
        MINIO_ENDPOINT: 's3://url.com'
      run: |
        aws configure set default.s3.signature_version s3v4
        aws --endpoint-url https://apis3.bnbdevelopment.cloud s3 cp myfile s3://jegyrendszer-app/newfile2 --debug
